engines:
  pep8:
    enabled: true

  markdownlint:
    enabled: true

  sonar-python:
    enabled: true
  
  csslint:
    enabled: true

  duplication:
    enabled: false

exclude_patterns:
  - "**/test/"
  - "**/.venv/"
  - "**/.vscode/"
  - "**/staticfiles/"