version: "3.7"
services:
  db:
    image: postgres:10.1-alpine
  web:
    build:
      context: .
      dockerfile: DockerfileTest
    ports:
      - "5005:5005"
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["./wait-for-it.sh", "${DB_HOST}:${DB_PORT}", "-t", "120", "--", "./base_site.sh"]

  bot:
    build:
      context: .
      dockerfile: DockerfileTest
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
      - web
    command:
      [
        "./wait-for-it.sh",
        "web:5005",
        "-t",
        "120",
        "--",
        "./wait-for-it.sh",
        "${DB_HOST}:${DB_PORT}",
        "-t",
        "120",
        "--",
        "python",
        "manage.py",
        "startelegrambot2",
      ]


  integration-tests:
    image: python:3.7.4-slim
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      sh -c "pip install tox && cd app && tox && find . -name '*.pyc' -delete && rm -rf .tox"
