name: Docker Image CI

on: [pull_request]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Integration Tests
      run: docker-compose up --exit-code-from integration-tests integration-tests
